server:
  port: 8761

eureka:
  instance:
    hostname: host.docker.internal
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://host.docker.internal:${server.port}/eureka/

info:
  application:
    name: discovery-service
    description: Openjob Discovery Server
    version: 0.0.1-SNAPSHOT