server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8080
          predicates:
            - Path=/prs/**
          filters:
            - RewritePath=/prs(?<segment>/?.*), /prs/patientData$\\{segment}
        - id: doctor-service
          uri: http://localhost:8083
          predicates:
            - Path=/drs/**
          filters:
            - RewritePath=/drs(?<segment>/?.*), /drs/doctorData$\\{segment}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
