# Use the official Tomcat image from the Docker Hub
FROM tomcat:9.0

# Remove the default webapps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy your WAR file to the Tomcat webapps directory
COPY target/appointmentSchedulingService.war /usr/local/tomcat/webapps/ROOT.war

# Expose port 8080 to the outside world
EXPOSE 8083

# Run Tomcat
CMD ["catalina.sh", "run"]